spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/product-service
      auto-index-creation: true
server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG